name: .NET Framework Windows Forms Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup MSBuild environment
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore CMPG223_HomelessShelter.sln

      # Build the project/solution
      - name: Build
        run: msbuild CMPG223_HomelessShelter.sln /p:Configuration=Release
